# Slack configs
slack: 
  username   : 'LunchHunter' # the username that the menus will be posted with
  icon_emoji : ':fork_and_knife:' # the icon that is used for messages
  fallback: Today's Menus # is shown in slack notification instead of content of attached menus
  #channel: '#lunch' # optionally overwrite slack channel of webhook
# Restaurant configs
restaurants:
  - name: UBS Restaurant Flurhof
    url : https://ubs-flur.sv-restaurant.ch/en/menu/restaurant-flurhof/
    parser: ./parsers/svrestaurant
    color: '#e60100'
  - name: Siemens Cube
    url: https://clients.eurest.ch/cube/de/Food%20Court
    client: ./clients/eurest
    id : 289
    color: '#009999'