# Slack configs
slack: 
  username   : 'LunchHunter' # the username that the menus will be posted with
  icon_emoji : ':fork_and_knife:' # the icon that is used for messages
  fallback: Today's Menus # is shown in slack notification instead of content of attached menus
  #channel: '#lunch' # optionally overwrite slack channel of webhook
# Restaurant configs
restaurants:
  - name: Swisscom Restaurant Binz
    url : http://swisscom-binz.sv-restaurant.ch/de.html
    color: '#173B81'
    parser: ./parsers/svrestaurant
  - name: Swiss Life Restaurant Binz49
    url : https://zfv.ch/de/microsites/swiss-life-restaurant-binz49/menueplan
    color: '#d82034'
    parser: ./parsers/zfv
  - name: Binz 38
    url : http://www.binz-38.ch/home/
    color: '#ec6730'
    parser: ./parsers/binz38
